### ISSUE TITLE
確認一下 FB 帳號是否為本人所擁有。

### ISSUE THREAD

**Issue by milochen0418** [johnroyer/crawler-php#11]
我看你 FB 有加我這個，但不確定是否為本人之真帳號
在沒有其它聯絡管道下，想說就在 GitHub 中 post 確認一下
請問如下連結這個是你本人在用的 FB 嗎?
https://www.facebook.com/profile.php?id=61557288808355

**Comment by johnroyer** [comment]
不要放跟專案無關的連結啊

這樣做其實也不能確認是本人 XD
